name: Test

on:
  pull_request:
  push:
    branches:
    - main

env:
  GOVERSION: 1.21.5

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GOVERSION }}
    - uses: golangci/golangci-lint-action@v3
      with:
        version: v1.54.2
        args: --timeout 4m

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: ${{ env.GOVERSION }}
    - run: go test -cover ./...
